{
 "title": "AppsPortal per server",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "show tag values from \"apps-portal.server.usage\" with key = \"host-name\""
   }
  ]
 },
 "panels": [
  {
   "title": "Connections to Vertica",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"active-connections\" FROM \"apps-portal.vertica.statistics\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"idle-connections\" FROM \"apps-portal.vertica.statistics\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"total-connections\" FROM \"apps-portal.vertica.statistics\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Reporting aggregator run-time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"average-run-time\" FROM \"apps-portal.reporting-aggregator-statistics\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Reporting aggregator rows and runs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"row-count\"), 1s) AS \"rows\" FROM \"apps-portal.reporting-aggregator-statistics\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"run-count\"), 1s) AS \"runs\" FROM \"apps-portal.reporting-aggregator-statistics\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU user-time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"user-time\"), 1s) AS \"cpu-user-time\" FROM \"apps-portal.server.usage\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU system time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"system-time\"), 1s) AS \"cpu-system-time\" FROM \"apps-portal.server.usage\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"jvm.heap-used\") AS \"max-memory\" FROM \"apps-portal.server.usage\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"jvm.heap-used\") AS \"mean-memory\" FROM \"apps-portal.server.usage\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Overall memory-in-use",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"memory-in-use\") AS \"memory-in-use\" FROM \"apps-portal.server.usage\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"jvm.gc-time\"), 1s) AS \"garbage-collection-time\" FROM \"apps-portal.server.usage\" WHERE \"host-name\" =~ /^($host)$/ AND $timeFilter GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}