{
 "title": "Cacheserves",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Aggregate QPS (Overall)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"qps\") AS \"aggregte-qps\" FROM (SELECT non_negative_derivative(min(\"requests-received\"), 1s) AS \"qps\" FROM \"cacheserve.server.statistics\" WHERE $timeFilter GROUP BY time($interval), \"node-id\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Aggregate TCP QPS (Overall)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"tcp-qps\") AS \"aggregte-tcp-qps\" FROM (SELECT non_negative_derivative(min(\"tcp-requests-received\"), 1s) AS \"tcp-qps\" FROM \"cacheserve.server.statistics\" WHERE $timeFilter GROUP BY time($interval), \"node-id\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Aggregate DoH QPS (Overall)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"doh-qps\") AS \"aggregte-doh-qps\" FROM (SELECT non_negative_derivative(min(\"https-requests-received\"), 1s) AS \"doh-qps\" FROM \"cacheserve.server.statistics\" WHERE $timeFilter GROUP BY time($interval), \"node-id\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Aggregate QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"qps\") AS \"aggregte-qps\" FROM (SELECT non_negative_derivative(min(\"requests-received\"), 1s) AS \"qps\" FROM \"cacheserve.server.statistics\" WHERE \"host-name\" != '' AND $timeFilter GROUP BY time($interval), \"host-name\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "QPS by Host",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"requests-received\"), 1s) AS \"qps\" FROM \"cacheserve.server.statistics\" WHERE \"host-name\" != '' AND $timeFilter GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CS 7.1.0 QPS (Only needed for old data)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Aggregate QPS (7.1.0)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT SUM(\"qps\") AS \"aggregate-qps\" FROM (SELECT non_negative_derivative(min(\"requests-received\"), 1s) AS \"qps\" FROM \"cacheserve.server.statistics\" WHERE \"host-name\" = '' AND $timeFilter GROUP BY time($interval), \"node-id\" fill(null)) WHERE $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "QPS by Node-id (7.1.0)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(min(\"requests-received\"), 1s) AS \"qps\" FROM \"cacheserve.server.statistics\" WHERE \"host-name\" = '' AND $timeFilter GROUP BY time($interval), \"node-id\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Aggregate Lookup Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"lps\") AS \"aggregate-lookups\" FROM (SELECT non_negative_derivative(min(\"lookups\"), 1s) AS \"lps\" FROM \"cacheserve.server.statistics\" WHERE $timeFilter GROUP BY time($interval), \"node-id\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Requests to Other DNS Servers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"rsps\") AS \"requests-sent\" FROM (SELECT non_negative_derivative(min(\"requests-sent\"), 1s) AS \"rsps\" FROM \"cacheserve.server.statistics\" WHERE $timeFilter GROUP BY time($interval), \"node-id\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"rrps\") AS \"responses-received\" FROM (SELECT non_negative_derivative(min(\"responses-received\"), 1s) AS \"rrps\" FROM \"cacheserve.server.statistics\" WHERE $timeFilter GROUP BY time($interval), \"node-id\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Rate-Limited Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"rlq\") AS \"rate-limited-requests\" FROM (SELECT non_negative_derivative(min(\"rate-limited-requests\"), 1s) AS \"rlq\" FROM \"cacheserve.server.statistics\" WHERE $timeFilter GROUP BY time($interval), \"node-id\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Suppressed or Dropped Queries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"mrd\") AS \"malformed-requests-dropped\" FROM (SELECT non_negative_derivative(min(\"malformed-requests-dropped\"), 1s) AS \"mrd\" FROM \"cacheserve.server.statistics\" WHERE $timeFilter GROUP BY time($interval), \"node-id\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"fld\") AS \"formerr-loop-dropped\" FROM (SELECT non_negative_derivative(min(\"formerr-loop-dropped\"), 1s) AS \"fld\" FROM \"cacheserve.server.statistics\" WHERE $timeFilter GROUP BY time($interval), \"node-id\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"sdq\") AS \"suppressed-duplicate-queries\" FROM (SELECT non_negative_derivative(min(\"suppressed-duplicate-queries\"), 1s) AS \"sdq\" FROM \"cacheserve.server.statistics\" WHERE $timeFilter GROUP BY time($interval), \"node-id\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"nv\") AS \"no-view\" FROM (SELECT non_negative_derivative(min(\"requests-no-view\"), 1s) AS \"nv\" FROM \"cacheserve.server.statistics\" WHERE $timeFilter GROUP BY time($interval), \"node-id\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Recursion Contexts in Use",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"rc\") AS \"recursion-contexts-in-use\" FROM (SELECT min(\"recursion-contexts-in-use\") AS \"rc\" FROM \"cacheserve.server.statistics\" WHERE $timeFilter GROUP BY time($interval), \"node-id\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TCP",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"tca\") AS \"tcp-connections-accepted\" FROM (SELECT non_negative_derivative(min(\"tcp-connections-accepted\"), 1s) AS \"tca\" FROM \"cacheserve.server.statistics\" WHERE $timeFilter GROUP BY time($interval), \"node-id\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"tcr\") AS \"tcp-connections-rejected\" FROM (SELECT non_negative_derivative(min(\"tcp-connections-rejected\"), 1s) AS \"tcr\" FROM \"cacheserve.server.statistics\" WHERE $timeFilter GROUP BY time($interval), \"node-id\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"tc\") AS \"tcp-clients\" FROM (SELECT min(\"tcp-clients\") AS \"tc\" FROM \"cacheserve.server.statistics\" WHERE $timeFilter GROUP BY time($interval), \"node-id\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"trs\") AS \"tcp-requests-sent\" FROM (SELECT non_negative_derivative(min(\"tcp-requests-sent\"), 1s) AS \"trs\" FROM \"cacheserve.server.statistics\" WHERE $timeFilter GROUP BY time($interval), \"node-id\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Aggregate prefetch-extension Rate on \"world\" resolver",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (SUM(\"prefetch-extensions\")) AS \"prefetch-extensions\" FROM (SELECT non_negative_derivative(min(\"prefetch-extensions\"), 1s) AS \"prefetch-extensions\" FROM \"cacheserve.resolver.statistics\" WHERE \"key\" = 'world' AND $timeFilter GROUP BY time($interval), \"host-name\" fill(null)) WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Prefetch-Extension Rate on \"world\" resolver by Host",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"prefetch-extensions\"), 1s) AS \"prefetch-extensions\" FROM \"cacheserve.resolver.statistics\" WHERE \"host-name\" != '' AND \"key\" = 'world' AND $timeFilter GROUP BY time($interval), \"host-name\", \"key\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Aggregate pm-resolver Response Rate by rcode (expensive query)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 }
  },
  {
   "title": "Aggregate \"world\" resolver Response Rate by rcode",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"rps\") AS \"queries-per-second\" FROM (SELECT non_negative_derivative(sum(\"rcode-value\"), 1s) AS \"rps\" FROM \"cacheserve.resolver.statistics\" WHERE \"host-name\" != '' AND \"key\" = 'world' AND $timeFilter GROUP BY time($interval), \"host-name\", rcode fill(null)) where $timeFilter group by time($interval), rcode fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Aggregate \"world\" resolver Query Rate by qtype",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"rps\") AS \"queries-per-second\" FROM (SELECT non_negative_derivative(sum(\"qtype-value\"), 1s) AS \"rps\" FROM \"cacheserve.resolver.statistics\" WHERE \"host-name\" != '' AND \"key\" = 'world' AND $timeFilter GROUP BY time($interval), \"host-name\", qtype fill(null)) where $timeFilter group by time($interval), qtype fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Aggregate \"world\" resolver DNSSEC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"dnssec-ok\") AS \"dnssec-validation-ok\" FROM (SELECT non_negative_derivative(sum(\"dnssec-validations-success\"), 1s) AS \"dnssec-ok\" FROM \"cacheserve.resolver.statistics\" WHERE \"host-name\" != '' AND \"key\" = 'world' AND $timeFilter GROUP BY time($interval), \"host-name\") where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"dnssec-nok\") AS \"dnssec-validation-fail\" FROM (SELECT non_negative_derivative(sum(\"dnssec-validations-failure\"), 1s) AS \"dnssec-nok\" FROM \"cacheserve.resolver.statistics\" WHERE \"host-name\" != '' AND \"key\" = 'world' AND $timeFilter GROUP BY time($interval), \"host-name\") where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"dnssec-ins\") AS \"dnssec-validation-insecure\" FROM (SELECT non_negative_derivative(sum(\"dnssec-validations-insecure\"), 1s) AS \"dnssec-ins\" FROM \"cacheserve.resolver.statistics\" WHERE \"host-name\" != '' AND \"key\" = 'world' AND $timeFilter GROUP BY time($interval), \"host-name\") where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"dnssec-no-needed\") AS \"dnssec-validation-not-needed\" FROM (SELECT non_negative_derivative(sum(\"dnssec-validations-not-needed\"), 1s) AS \"dnssec-no-needed\" FROM \"cacheserve.resolver.statistics\" WHERE \"host-name\" != '' AND \"key\" = 'world' AND $timeFilter GROUP BY time($interval), \"host-name\") where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Cacheserve Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Cacheserve Memory by Hostname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT min(\"memory-in-use\") AS \"memory\" FROM \"cacheserve.server.usage\" WHERE $timeFilter GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}