{
 "title": "Cacheserve per server",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Cacheserve Hostname",
    "query": "show tag values from \"cacheserve.server.statistics\" with key = \"host-name\""
   }
  ]
 },
 "panels": [
  {
   "title": "Requests-Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"requests-received\"), 1s) AS \"qps\" FROM \"cacheserve.server.statistics\" WHERE \"host-name\" =~ /^($hostname)$/ AND $timeFilter GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"tcp-requests-received\"), 1s) AS \"tcp-qps\" FROM \"cacheserve.server.statistics\" WHERE \"host-name\" =~ /^($hostname)$/ AND $timeFilter GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"tls-requests-received\"), 1s) AS \"tls-qps\" FROM \"cacheserve.server.statistics\" WHERE \"host-name\" =~ /^($hostname)$/ AND $timeFilter GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"https-requests-received\"), 1s) AS \"doh-qps\" FROM \"cacheserve.server.statistics\" WHERE \"host-name\" =~ /^($hostname)$/ AND $timeFilter GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lookups",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"lookups\"), 1s) AS \"lps\" FROM \"cacheserve.server.statistics\" WHERE $timeFilter AND \"host-name\" =~ /^($hostname)$/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rate Limited Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"rate-limited-requests\"), 1s) AS \"rlq\" FROM \"cacheserve.server.statistics\" WHERE $timeFilter AND \"host-name\" =~ /^($hostname)$/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Recursion Contexts In Use",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT min(\"recursion-contexts-in-use\") AS \"rc\" FROM \"cacheserve.server.statistics\" WHERE $timeFilter AND \"host-name\" =~ /^($hostname)$/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Prefetch Extensions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"prefetch-extensions\"), 1s) AS \"prefetch-extensions\" FROM \"cacheserve.resolver.statistics\" WHERE \"key\" = 'world' AND $timeFilter AND \"host-name\" =~ /^($hostname)$/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Suppressed or Dropped Queries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"malformed-requests-dropped\"), 1s) AS \"malformed-requests-dropped\" FROM \"cacheserve.server.statistics\" WHERE $timeFilter AND \"host-name\" =~ /^($hostname)$/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"formerr-loop-dropped\"), 1s) AS \"formerr-loop-dropped\" FROM \"cacheserve.server.statistics\" WHERE $timeFilter AND \"host-name\" =~ /^($hostname)$/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"suppressed-duplicate-queries\"), 1s) AS \"suppressed-duplicate-queries\" FROM \"cacheserve.server.statistics\" WHERE $timeFilter AND \"host-name\" =~ /^($hostname)$/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"requests-no-view\"), 1s) AS \"no-view\" FROM \"cacheserve.server.statistics\" WHERE $timeFilter AND \"host-name\" =~ /^($hostname)$/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TCP",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"tcp-connections-accepted\"), 1s) AS \"tcp-connections-accepted\" FROM \"cacheserve.server.statistics\" WHERE $timeFilter AND \"host-name\" =~ /^($hostname)$/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"tcp-connections-rejected\"), 1s) AS \"tcp-connections-rejected\" FROM \"cacheserve.server.statistics\" WHERE $timeFilter AND \"host-name\" =~ /^($hostname)$/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"tcp-clients\"), 1s) AS \"tcp-clients\" FROM \"cacheserve.server.statistics\" WHERE $timeFilter AND \"host-name\" =~ /^($hostname)$/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"tcp-requests-sent\"), 1s) AS \"tcp-requests-sent\" FROM \"cacheserve.server.statistics\" WHERE $timeFilter AND \"host-name\" =~ /^($hostname)$/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Response Rate by rcode",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(sum(\"rcode-value\"), 1s) AS \"rps\" FROM \"cacheserve.resolver.statistics\" WHERE \"host-name\" =~ /^($hostname)$/ AND \"key\" = 'world' AND $timeFilter GROUP BY time($interval), \"host-name\", rcode fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Response Rate by qtype",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(sum(\"qtype-value\"), 1s) AS \"rps\" FROM \"cacheserve.resolver.statistics\" WHERE \"host-name\" =~ /^($hostname)$/ AND \"key\" = 'world' AND $timeFilter GROUP BY time($interval), \"host-name\", qtype fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT min(\"memory-in-use\") AS \"memory\" FROM \"cacheserve.server.usage\" WHERE $timeFilter AND \"host-name\" =~ /^($hostname)$/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Provisioning Update Lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (min(\"kafka-provisioning.current-time\") - min(\"kafka-provisioning.last-update-time\")) AS \"update lag\" FROM \"cacheserve.layer.status\" WHERE $timeFilter AND \"host-name\" =~ /^($hostname)$/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Provisioning Heartbeat Lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (min(\"kafka-provisioning.current-time\") - min(\"kafka-provisioning.last-alive-time\")) AS \"hearbeats lag\" FROM \"cacheserve.layer.status\" WHERE $timeFilter AND \"host-name\" =~ /^($hostname)$/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT 1- (\"recursive-lookups\" / lookups) as \"cache-hit-rate\" FROM (SELECT non_negative_derivative(mean(\"recursive-lookups\"), 1s) AS \"recursive-lookups\", non_negative_derivative(mean(\"lookups\"), 1s) AS lookups FROM \"cacheserve.resolver.statistics\" WHERE $timeFilter AND \"host-name\" =~ /^($hostname)$/  GROUP BY time($__interval), \"host-name\" fill(null)) GROUP BY \"host-name\"  ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Auth Server Requests and Responses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"requests-sent\"), 1s) AS \"requests-sent\" FROM \"cacheserve.server.statistics\" WHERE $timeFilter AND \"host-name\" =~ /^($hostname)$/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"responses-received\"), 1s) AS \"responses-received\" FROM \"cacheserve.server.statistics\" WHERE $timeFilter AND \"host-name\" =~ /^($hostname)$/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}