{
 "title": "Flow-allocators",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Flow-allocator Requests Aggregate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"requests-received\") as \"aggregate-requests-received\" from (SELECT non_negative_derivative(min(\"flow-allocator.requests-received\"), 1s) AS \"requests-received\" from \"nom-proxy.server.statistics\" where $timeFilter group by time($interval), \"host-name\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"requests-forwarded\") AS \"aggregate-requests-forwarded\" FROM (SELECT non_negative_derivative(min(\"flow-allocator.requests-forwarded\"), 1s) AS \"requests-forwarded\" from \"nom-proxy.server.statistics\" where $timeFilter group by time($interval), \"host-name\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"invalid-requests-received\") AS \"aggregate-invalid-requests-received\" FROM (SELECT non_negative_derivative(min(\"flow-allocator.invalid-requests-received\"), 1s) AS \"invalid-requests-received\" from \"nom-proxy.server.statistics\" where $timeFilter group by time($interval), \"host-name\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"responses-failed\") AS \"aggregate-responses-failed\" FROM (SELECT non_negative_derivative(min(\"flow-allocator.responses-failed\"), 1s) AS \"responses-failed\" from \"nom-proxy.server.statistics\" where $timeFilter group by time($interval), \"host-name\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Flow-allocator Lookups Aggregate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"lookups-received\") as \"aggregate-lookups-received\" from (SELECT non_negative_derivative(min(\"flow-allocator.lookups-received\"), 1s) AS \"lookups-received\" from \"nom-proxy.server.statistics\" where $timeFilter group by time($interval), \"host-name\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"lookups-failed\") AS \"aggregate-lookups-failed\" FROM (SELECT non_negative_derivative(min(\"flow-allocator.lookups-failed\"), 1s) AS \"lookups-failed\" from \"nom-proxy.server.statistics\" where $timeFilter group by time($interval), \"host-name\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Flow-allocator Queries Aggregate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"queries-received\") as \"aggregate-queries-received\" from (SELECT non_negative_derivative(min(\"flow-allocator.queries-received\"), 1s) AS \"queries-received\" from \"nom-proxy.server.statistics\" where $timeFilter group by time($interval), \"host-name\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"queries-failed\") AS \"aggregate-queries-failed\" FROM (SELECT non_negative_derivative(min(\"flow-allocator.queries-failed\"), 1s) AS \"queries-failed\" from \"nom-proxy.server.statistics\" where $timeFilter group by time($interval), \"host-name\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Flow-allocator Connections Aggregate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"connections-received\") as \"aggregate-connections-received\" from (SELECT non_negative_derivative(min(\"flow-allocator.connections-received\"), 1s) AS \"connections-received\" from \"nom-proxy.server.statistics\" where $timeFilter group by time($interval), \"host-name\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}