{
 "title": "Flow-allocator per server",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": "show tag values from \"nom-proxy.server.statistics\" with key = \"host-name\""
   }
  ]
 },
 "panels": [
  {
   "title": "Flow-allocator Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"flow-allocator.requests-received\"), 1s) AS \"requests-received\" from \"nom-proxy.server.statistics\" where $timeFilter AND \"host-name\" =~ /^($hostname)$/ group by time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"flow-allocator.requests-forwarded\"), 1s) AS \"requests-forwarded\" from \"nom-proxy.server.statistics\" where $timeFilter AND \"host-name\" =~ /^($hostname)$/ group by time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"flow-allocator.invalid-requests-received\"), 1s) AS \"invalid-requests-received\" from \"nom-proxy.server.statistics\" where $timeFilter AND \"host-name\" =~ /^($hostname)$/ group by time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"flow-allocator.responses-failed\"), 1s) AS \"responses-failed\" from \"nom-proxy.server.statistics\" where $timeFilter AND \"host-name\" =~ /^($hostname)$/ group by time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Flow-allocator Lookups",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "lookups/s" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"flow-allocator.lookups-received\"), 1s) AS \"lookups-received\" from \"nom-proxy.server.statistics\" where $timeFilter AND \"host-name\" =~ /^($hostname)$/ group by time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"flow-allocator.lookups-failed\"), 1s) AS \"lookups-failed\" from \"nom-proxy.server.statistics\" where $timeFilter AND \"host-name\" =~ /^($hostname)$/ group by time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Flow-allocator Queries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "queries/s" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"flow-allocator.queries-received\"), 1s) AS \"queries-received\" from \"nom-proxy.server.statistics\" where $timeFilter AND \"host-name\" =~ /^($hostname)$/ group by time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"flow-allocator.queries-failed\"), 1s) AS \"queries-failed\" from \"nom-proxy.server.statistics\" where $timeFilter AND \"host-name\" =~ /^($hostname)$/ group by time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Flow-allocator Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "connections/s" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"flow-allocator.connections-received\"), 1s) AS \"connections-received\" from \"nom-proxy.server.statistics\" where $timeFilter AND \"host-name\" =~ /^($hostname)$/ group by time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}