{
 "title": "IP Tracker per server",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "nodeid",
    "query": "show tag values from \"iptracker.server.statistics\" with key = \"node-id\""
   },
   {
    "name": "host",
    "query": "show tag values from \"iptracker.server.statistics\" with key = \"host-name\""
   }
  ]
 },
 "panels": [
  {
   "title": "RADIUS Packet Rates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"p-r\") AS \"received\" FROM( SELECT non_negative_derivative(min(\"packets-received\"), 1s) AS \"p-r\" FROM \"iptracker.radius.statistics\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY time($interval), \"host-name\" fill(null)) WHERE $timeFilter GROUP BY time($interval), \"host-name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"p-d\") AS \"dropped\" FROM( SELECT non_negative_derivative(min(\"packets-dropped\"), 1s) AS \"p-d\" FROM \"iptracker.radius.statistics\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY time($interval), \"host-name\" fill(null)) WHERE $timeFilter GROUP BY time($interval), \"host-name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"p-s\") AS \"sent\" FROM( SELECT non_negative_derivative(min(\"packets-sent\"), 1s) AS \"p-s\" FROM \"iptracker.radius.statistics\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY time($interval), \"host-name\" fill(null)) WHERE $timeFilter GROUP BY time($interval), \"host-name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RADIUS Message Rates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"r-s\") AS \"starts\" FROM( SELECT non_negative_derivative(min(\"starts\"), 1s) AS \"r-s\" FROM \"iptracker.radius.statistics\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY time($interval), \"host-name\" fill(null)) WHERE $timeFilter GROUP BY time($interval), \"host-name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"r-stops\") AS \"stops\" FROM( SELECT non_negative_derivative(min(\"stops\"), 1s) AS \"r-stops\" FROM \"iptracker.radius.statistics\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY time($interval), \"host-name\" fill(null)) WHERE $timeFilter GROUP BY time($interval), \"host-name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"r-i-u\") AS \"interim\" FROM( SELECT non_negative_derivative(min(\"interim-updates\"), 1s) AS \"r-i-u\" FROM \"iptracker.radius.statistics\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY time($interval), \"host-name\" fill(null)) WHERE $timeFilter GROUP BY time($interval), \"host-name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP API",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"http-requests\") AS \"http-requests\" FROM( SELECT non_negative_derivative(min(\"http.requests\"), 1s) AS \"http-requests\" FROM \"iptracker.server.statistics\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY time($interval), \"host-name\" fill(null)) WHERE $timeFilter GROUP BY time($interval), \"host-name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"http-adds\") AS \"http-adds\" FROM( SELECT non_negative_derivative(min(\"http.adds\"), 1s) AS \"http-adds\" FROM \"iptracker.server.statistics\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY time($interval), \"host-name\" fill(null)) WHERE $timeFilter GROUP BY time($interval), \"host-name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"http-deletes\") AS \"http-deletes\" FROM( SELECT non_negative_derivative(min(\"http.deletes\"), 1s) AS \"http-deletes\" FROM \"iptracker.server.statistics\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY time($interval), \"host-name\" fill(null)) WHERE $timeFilter GROUP BY time($interval), \"host-name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"http-fail\") AS \"http-fail\" FROM( SELECT non_negative_derivative(min(\"http.failures\"), 1s) AS \"http-fail\" FROM \"iptracker.server.statistics\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY time($interval), \"host-name\" fill(null)) WHERE $timeFilter GROUP BY time($interval), \"host-name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU user-time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"user-time\"), 1s) AS \"cpu-user-time\" FROM \"iptracker.server.usage\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU system time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"system-time\"), 1s) AS \"cpu-system-time\" FROM \"iptracker.server.usage\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"jvm.heap-used\") AS \"max-memory\" FROM \"iptracker.server.usage\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Provisioning lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"current-time\" - \"last-update-time\" AS \"provisioning lag\" FROM \"iptracker.provisioner.statistics\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Provisioning messages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "msg/s" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"messages-added\"), 1s) AS \"messages-added\" FROM \"iptracker.provisioner.statistics\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"messages-deleted\"), 1s) AS \"messages-deleted\" FROM \"iptracker.provisioner.statistics\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"messages-delivered\"), 1s) AS \"messages-delivered\" FROM \"iptracker.provisioner.statistics\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"messages-dropped\"), 1s) AS \"messages-dropped\" FROM \"iptracker.provisioner.statistics\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"jvm.gc-time\"), 1s) AS \"garbage-collection-time\" FROM \"iptracker.server.usage\" WHERE \"host-name\" =~ /^($host)$/ AND $timeFilter GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}