{
 "title": "NLM per server",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "show tag values from \"nom-list-manager.server.information\" with key = \"host-name\""
   }
  ]
 },
 "panels": [
  {
   "title": "Memory usage by LS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"memory-in-use\") AS \"memory-in-use\" FROM \"nom-list-manager.list-service-list.statistics\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failure count by LS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"failure-count\") AS \"failure-count\" FROM \"nom-list-manager.list-service.watchdog\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory usage by Postgres",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"memory-in-use\") AS \"memory-in-use\" FROM \"nom-list-manager.postgres.statistics\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Connections to Postgres",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"statistics.active-connections\") AS \"active-connections\" FROM \"nom-list-manager.postgres.statistics\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"statistics.total-connections\") AS \"total-connections\" FROM \"nom-list-manager.postgres.statistics\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failure count by Postgres",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"failure-count\") AS \"failure-count\" FROM \"nom-list-manager.postgres.watchdog\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory usage by LL",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"memory-in-use\") AS \"memory-in-use\" FROM \"nom-list-manager.local-service-list.statistics\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory usage by LA",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"memory-in-use\") AS \"memory-in-use\" FROM \"nom-list-manager.local-service-address.statistics\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}