{
 "title": "Nom-Data-Loader per server",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": "show tag values from \"nom-data-loader.server.statistics\" with key = \"host-name\""
   }
  ]
 },
 "panels": [
  {
   "title": "Bytes Loaded / Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host-name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nom-data-loader.loader.statistics",
     "query": "SELECT non_negative_derivative(min(\"bytes-loaded\"), 1s) AS \"bytes_loaded\" FROM \"nom-data-loader.loader.statistics\" WHERE \"host-name\" =~ /$hostname/ AND $timeFilter GROUP BY time($interval), \"host-name\", \"key\" fill(null)",
     "select": [
      [
       { "params": [ "all-loaders.rows-loaded" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host-name", "operator": "=", "value": "engdb02-1.eng-lab.nominum.com" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host-name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nom-data-loader.loader.statistics",
     "query": "SELECT SUM(bytes) AS total_bytes_loaded FROM (SELECT non_negative_derivative(min(\"bytes-loaded\"), 1s) AS bytes FROM \"nom-data-loader.loader.statistics\" WHERE \"host-name\" =~ /$hostname/ AND $timeFilter GROUP BY time(60s), \"host-name\",\"key\" fill(null)) WHERE $timeFilter GROUP BY time(60s)",
     "select": [
      [
       { "params": [ "all-loaders.rows-loaded" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host-name", "operator": "=", "value": "engdb02-1.eng-lab.nominum.com" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host-name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nom-data-loader.loader.statistics",
     "query": "select mean(total_bytes_loaded) as \"1h_mean\" from (SELECT SUM(bytes) AS total_bytes_loaded FROM (SELECT non_negative_derivative(min(\"bytes-loaded\"), 1s) AS bytes FROM \"nom-data-loader.loader.statistics\" WHERE \"host-name\" =~ /$hostname/ AND $timeFilter GROUP BY time(60s), \"host-name\",\"key\" fill(null)) WHERE $timeFilter GROUP BY time(60s)) where $timeFilter group by time(1h) fill(null)",
     "select": [
      [
       { "params": [ "all-loaders.rows-loaded" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host-name", "operator": "=", "value": "engdb02-1.eng-lab.nominum.com" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host-name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nom-data-loader.loader.statistics",
     "query": "select mean(total_bytes_loaded) as \"10m_mean\" from (SELECT SUM(bytes) AS total_bytes_loaded FROM (SELECT non_negative_derivative(min(\"bytes-loaded\"), 1s) AS bytes FROM \"nom-data-loader.loader.statistics\" WHERE \"host-name\" =~ /$hostname/ AND $timeFilter GROUP BY time(60s), \"host-name\",\"key\" fill(null)) WHERE $timeFilter GROUP BY time(60s)) where $timeFilter group by time(10m) fill(null)",
     "select": [
      [
       { "params": [ "all-loaders.rows-loaded" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host-name", "operator": "=", "value": "engdb02-1.eng-lab.nominum.com" }
     ]
    }
   ]
  },
  {
   "title": "Rows Loaded / Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host-name" ], "type": "tag" },
      { "params": [ "key" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nom-data-loader.loader.statistics",
     "select": [
      [
       { "params": [ "rows-loaded" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "rows/sec" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host-name", "operator": "=~", "value": "/$hostname/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host-name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nom-data-loader.loader.statistics",
     "query": "select sum(rps) as total_rps from (SELECT non_negative_derivative(min(\"rows-loaded\"), 1s) AS \"rps\" FROM \"nom-data-loader.loader.statistics\" WHERE \"host-name\" =~ /$hostname/ AND $timeFilter GROUP BY time(60s), \"host-name\",\"key\") where $timeFilter group by time(60s) fill(null)",
     "select": [
      [
       { "params": [ "rows-loaded" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "rows/sec" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host-name", "operator": "=~", "value": "/engdb/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host-name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nom-data-loader.loader.statistics",
     "query": "select mean(rps) as \"1h_mean\" from (select sum(rps) as \"rps\" from (SELECT non_negative_derivative(min(\"rows-loaded\"), 1s) AS \"rps\" FROM \"nom-data-loader.loader.statistics\" WHERE \"host-name\" =~ /$hostname/ AND $timeFilter GROUP BY time(60s), \"host-name\",\"key\") where $timeFilter group by time(60s) fill(null)) where $timeFilter group by time(1h) fill(null)",
     "select": [
      [
       { "params": [ "rows-loaded" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "rows/sec" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host-name", "operator": "=~", "value": "/engdb/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host-name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nom-data-loader.loader.statistics",
     "query": "select mean(rps) as \"10m_mean\" from (select sum(rps) as \"rps\" from (SELECT non_negative_derivative(min(\"rows-loaded\"), 1s) AS \"rps\" FROM \"nom-data-loader.loader.statistics\" WHERE \"host-name\" =~ /$hostname/ AND $timeFilter GROUP BY time(60s), \"host-name\",\"key\") where $timeFilter group by time(60s) fill(null)) where $timeFilter group by time(10m) fill(null)",
     "select": [
      [
       { "params": [ "rows-loaded" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "rows/sec" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host-name", "operator": "=~", "value": "/engdb/" }
     ]
    }
   ]
  },
  {
   "title": "Vertica CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "% of total " }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "vertica-node-id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nom-data-loader.vertica.statistics",
     "query": "SELECT max(\"cpu-usage\") AS \"node\" FROM \"nom-data-loader.vertica.statistics\" WHERE (\"host-name\" =~ /$hostname/) AND $timeFilter GROUP BY time($interval), \"vertica-node-id\" fill(null)",
     "select": [
      [
       { "params": [ "cpu-usage" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "node" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host-name", "operator": "=~", "value": "/$hostname/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nom-data-loader.vertica.statistics",
     "select": [
      [
       { "params": [ "cpu-usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "mean" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host-name", "operator": "=~", "value": "/$hostname/" }
     ]
    }
   ]
  },
  {
   "title": "Kafka Consumer Lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "messages" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host-name" ], "type": "tag" },
      { "params": [ "key" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nom-data-loader.loader.statistics",
     "select": [
      [
       {
        "params": [
         "kafka-metrics.consumer-fetch-manager-metrics.records-lag-max"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host-name", "operator": "=~", "value": "/$hostname/" }
     ]
    }
   ]
  },
  {
   "title": "Number of queries queued",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nom-data-loader.vertica-resource-queue-statistics",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "queued-count" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host-name", "operator": "=~", "value": "/^$hostname/" }
     ]
    }
   ]
  },
  {
   "title": "ROS MB Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host-name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nom-data-loader.vertica.statistics",
     "query": "SELECT max(\"ros-used-bytes\") / (1024*1024) as mb_used FROM \"nom-data-loader.vertica.statistics\" WHERE $timeFilter AND \"host-name\" =~ /$hostname/ GROUP BY time($interval), \"vertica-node-id\" fill(null)",
     "select": [
      [
       { "params": [ "ros-used-bytes" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ROS Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "vertica-node-id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nom-data-loader.vertica.statistics",
     "select": [
      [
       { "params": [ "ros-count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host-name", "operator": "=~", "value": "/$hostname/" }
     ]
    }
   ]
  },
  {
   "title": "Average Copy Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host-name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nom-data-loader.loader.statistics",
     "query": "SELECT mean(\"average-processing-time\") FROM \"nom-data-loader.loader.statistics\" WHERE (\"host-name\" =~ /$hostname/) AND $timeFilter GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "average-processing-time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host-name", "operator": "=~", "value": "/$hostname/" }
     ]
    }
   ]
  },
  {
   "title": "Vertica IO",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "vertica-node-id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nom-data-loader.vertica.statistics",
     "query": "SELECT non_negative_derivative(min(\"io-write\"), 1s) AS \"writes\" FROM \"nom-data-loader.vertica.statistics\" WHERE (\"host-name\" =~ /$hostname/) AND $timeFilter GROUP BY time($interval), \"vertica-node-id\" fill(null)",
     "select": [
      [
       { "params": [ "io-write" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "writes" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host-name", "operator": "=~", "value": "/$hostname/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "vertica-node-id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nom-data-loader.vertica.statistics",
     "select": [
      [
       { "params": [ "io-read" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "reads" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host-name", "operator": "=~", "value": "/$hostname/" }
     ]
    }
   ]
  },
  {
   "title": "Vertica Memory Usage (percent)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host-name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nom-data-loader.vertica.statistics",
     "query": "SELECT mean(\"memory-usage\") FROM \"nom-data-loader.vertica.statistics\" WHERE (\"host-name\" =~ /$hostname/) AND $timeFilter GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "memory-usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host-name", "operator": "=~", "value": "/$hostname/" }
     ]
    }
   ]
  },
  {
   "title": "data-loader messages processed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "messages" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host-name" ], "type": "tag" },
      { "params": [ "key" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nom-data-loader.loader.statistics",
     "query": "SELECT non_negative_derivative(min(\"messages-processed\"), 1s) FROM \"nom-data-loader.loader.statistics\" WHERE \"host-name\" =~ /$hostname/ AND $timeFilter GROUP BY time($interval), \"host-name\", \"key\" fill(null)",
     "select": [
      [
       { "params": [ "messages-processed" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host-name", "operator": "=~", "value": "/$hostname/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(total) AS \"total\" FROM (SELECT non_negative_derivative(min(\"messages-processed\"), 1s) AS \"total\" FROM \"nom-data-loader.loader.statistics\" WHERE \"host-name\" =~ /$hostname/ AND $timeFilter GROUP BY time($interval), \"host-name\", \"key\" fill(null)) WHERE $timeFilter GROUP BY time(60s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Loader Pool Running Queries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host-name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nom-data-loader.vertica.resource-pool-statistics",
     "select": [
      [
       { "params": [ "running-query-count-avg" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "avg" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host-name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nom-data-loader.vertica.resource-pool-statistics",
     "select": [
      [
       { "params": [ "running-query-count-max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "max" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Vertica Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "cluster-id" ], "type": "tag" },
      { "params": [ "vertica-node-id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nom-data-loader.vertica.statistics",
     "query": "select max(event) AS \"fault-tolerance-critical\" from (select non_negative_derivative(min(\"monitoring-events.fault-tolerance-critical\"), 30s) as event from \"nom-data-loader.vertica.statistics\" where $timeFilter and \"cluster-id\" != \"\" group by time(30s), \"vertica-node-id\", \"cluster-id\") WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "monitoring-events.too-many-ros-containers"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" },
       { "params": [ "too-many-ros" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host-name", "operator": "=~", "value": "/engdb/" },
      { "condition": "AND", "key": "cluster-id", "operator": "!=", "value": "1493247123:372539945" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "cluster-id" ], "type": "tag" },
      { "params": [ "vertica-node-id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nom-data-loader.vertica.statistics",
     "query": "select max(event) AS \"loss-of-k-safety\" from (select non_negative_derivative(min(\"monitoring-events.loss-of-k-safety\"), 30s) as event from \"nom-data-loader.vertica.statistics\" where $timeFilter and \"cluster-id\" != \"\" group by time(30s), \"vertica-node-id\", \"cluster-id\") WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "monitoring-events.too-many-ros-containers"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" },
       { "params": [ "too-many-ros" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host-name", "operator": "=~", "value": "/engdb/" },
      { "condition": "AND", "key": "cluster-id", "operator": "!=", "value": "1493247123:372539945" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "cluster-id" ], "type": "tag" },
      { "params": [ "vertica-node-id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nom-data-loader.vertica.statistics",
     "query": "select max(event) AS \"too-many-ros-containers\" from (select non_negative_derivative(min(\"monitoring-events.too-many-ros-containers\"), 30s) as event from \"nom-data-loader.vertica.statistics\" where $timeFilter and \"cluster-id\" != \"\" group by time(30s), \"vertica-node-id\", \"cluster-id\") WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "monitoring-events.too-many-ros-containers"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" },
       { "params": [ "too-many-ros" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host-name", "operator": "=~", "value": "/engdb/" },
      { "condition": "AND", "key": "cluster-id", "operator": "!=", "value": "1493247123:372539945" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "cluster-id" ], "type": "tag" },
      { "params": [ "vertica-node-id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nom-data-loader.vertica.statistics",
     "query": "select max(event) AS \"node-state-change\" from (select non_negative_derivative(min(\"monitoring-events.node-state-change\"), 30s) as event from \"nom-data-loader.vertica.statistics\" where $timeFilter and \"cluster-id\" != \"\" group by time(30s), \"vertica-node-id\", \"cluster-id\") WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "monitoring-events.too-many-ros-containers"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" },
       { "params": [ "too-many-ros" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host-name", "operator": "=~", "value": "/engdb/" },
      { "condition": "AND", "key": "cluster-id", "operator": "!=", "value": "1493247123:372539945" }
     ]
    }
   ]
  }
 ]
}