{
 "title": "NSM per server",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "show tag values from \"nom-service-monitor.server.statistics\" with key = \"host-name\""
   },
   {
    "name": "condition",
    "query": "show tag values from \"nom-service-monitor.telemetry-condition.statistics\" with key = \"key\""
   }
  ]
 },
 "panels": [
  {
   "title": "Telemetry presence monitoring",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"condition-triggers-error\"), 5s) AS \"errors\" FROM \"nom-service-monitor.presence-condition.statistics\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ AND \"key\" =~ /telemetry-presence/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"condition-triggers-warn\"), 5s) AS \"warns\" FROM \"nom-service-monitor.presence-condition.statistics\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ AND \"key\" =~ /telemetry-presence/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"condition-clears\"), 5s) AS \"clears\" FROM \"nom-service-monitor.presence-condition.statistics\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ AND \"key\" =~ /telemetry-presence/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "License expiration monitoring",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"condition-triggers-error\"), 5s) AS \"errors\" FROM \"nom-service-monitor.license-condition.statistics\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ AND \"key\" =~ /license-expiration/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"condition-triggers-warn\"), 5s) AS \"warns\" FROM \"nom-service-monitor.license-condition.statistics\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ AND \"key\" =~ /license-expiration/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"condition-clears\"), 5s) AS \"clears\" FROM \"nom-service-monitor.license-condition.statistics\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ AND \"key\" =~ /license-expiration/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Telemetry conditions errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"condition-triggers-error\"), 5s) AS \"errors\" FROM \"nom-service-monitor.telemetry-condition.statistics\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ AND \"key\" =~ /^($condition)$/ GROUP BY time($interval), \"host-name\", \"key\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Telemetry conditions warns",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"condition-triggers-warn\"), 5s) AS \"warns\" FROM \"nom-service-monitor.telemetry-condition.statistics\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ AND \"key\" =~ /^($condition)$/ GROUP BY time($interval), \"host-name\", \"key\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Telemetry conditions clears",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"condition-clears\"), 5s) AS \"clears\" FROM \"nom-service-monitor.telemetry-condition.statistics\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ AND \"key\" =~ /^($condition)$/ GROUP BY time($interval), \"host-name\", \"key\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU user-time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"user-time\"), 1s) AS \"cpu-user-time\" FROM \"nom-service-monitor.server.usage\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU system time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"system-time\"), 1s) AS \"cpu-system-time\" FROM \"nom-service-monitor.server.usage\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"jvm.heap-used\") AS \"max-memory\" FROM \"nom-service-monitor.server.usage\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"jvm.heap-used\") AS \"mean-memory\" FROM \"nom-service-monitor.server.usage\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Overall memory-in-use",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"memory-in-use\") AS \"memory-in-use\" FROM \"nom-service-monitor.server.usage\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"jvm.gc-time\"), 1s) AS \"garbage-collection-time\" FROM \"nom-service-monitor.server.usage\" WHERE \"host-name\" =~ /^($host)$/ AND $timeFilter GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}