{
 "title": "Proxy per server",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": "show tag values from \"nom-proxy.server.statistics\" with key = \"host-name\""
   }
  ]
 },
 "panels": [
  {
   "title": "Total Bandwidth HTTP-Proxy",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"http.request-bytes-sent\"), 1s) + non_negative_derivative(min(\"http.request-bytes-received\"), 1s) + non_negative_derivative(min(\"http.response-bytes-received\"), 1s) + non_negative_derivative(min(\"http.response-bytes-sent\"), 1s) AS \"total-bytes\" from \"nom-proxy.server.statistics\" where $timeFilter AND \"host-name\" =~ /^($hostname)$/ group by time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Bandwidth TCP-Proxy",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"tcp.client-bytes-received\"), 1s) + non_negative_derivative(min(\"tcp.client-bytes-sent\"), 1s) + non_negative_derivative(min(\"tcp.server-bytes-received\"), 1s) + non_negative_derivative(min(\"tcp.server-bytes-sent\"), 1s) AS \"total-bytes\" from \"nom-proxy.server.statistics\" where $timeFilter AND \"host-name\" =~ /^($hostname)$/ group by time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Bandwidth UDP-Proxy",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"udp.client-bytes-received\"), 1s) + non_negative_derivative(min(\"udp.client-bytes-sent\"), 1s) + non_negative_derivative(min(\"udp.server-bytes-received\"), 1s) + non_negative_derivative(min(\"udp.server-bytes-sent\"), 1s) AS \"total-bytes\" from \"nom-proxy.server.statistics\" where $timeFilter AND \"host-name\" =~ /^($hostname)$/ group by time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Requests Received HTTP-Proxy",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select non_negative_derivative(min(\"http.requests-received\"), 1s) as \"http-requests-received\" from \"nom-proxy.server.statistics\" where $timeFilter AND \"host-name\" =~ /^($hostname)$/ group by time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Response by-status-code HTTP-Proxy",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select non_negative_derivative(min(\"http.policy-responses-sent\"), 1s) as \"policy-responses-sent\" from \"nom-proxy.server.statistics\" where $timeFilter AND \"host-name\" =~ /^($hostname)$/ group by time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select non_negative_derivative(min(\"http.policy-responses-sent-by-status.200\"), 1s) as \"http-response-200\" from \"nom-proxy.server.statistics\" where $timeFilter AND \"host-name\" =~ /^($hostname)$/ group by time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select non_negative_derivative(min(\"http.policy-responses-sent-by-status.302\"), 1s) as \"http-response-302\" from \"nom-proxy.server.statistics\" where $timeFilter AND \"host-name\" =~ /^($hostname)$/ group by time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select non_negative_derivative(min(\"http.policy-responses-sent-by-status.403\"), 1s) as \"http-response-403\" from \"nom-proxy.server.statistics\" where $timeFilter AND \"host-name\" =~ /^($hostname)$/ group by time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Stats TCP-Proxy",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select non_negative_derivative(min(\"tcp.connections-received\"), 1s) as \"tcp-connections-received\" from \"nom-proxy.server.statistics\" where $timeFilter AND \"host-name\" =~ /^($hostname)$/ group by time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select non_negative_derivative(min(\"tcp.connections-proxied\"), 1s) as \"tcp-connections-proxied\" from \"nom-proxy.server.statistics\" where $timeFilter AND \"host-name\" =~ /^($hostname)$/ group by time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select non_negative_derivative(min(\"tcp.connections-denied\"), 1s) as \"tcp-connections-denied\" from \"nom-proxy.server.statistics\" where $timeFilter AND \"host-name\" =~ /^($hostname)$/ group by time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select non_negative_derivative(min(\"tcp.connections-failed-lookup\"), 1s) + non_negative_derivative(min(\"tcp.connections-failed-upstream\"), 1s) + non_negative_derivative(min(\"tcp.connections-no-flow-allocator\"), 1s) as \"tcp-connections-failed\" from \"nom-proxy.server.statistics\" where $timeFilter AND \"host-name\" =~ /^($hostname)$/ group by time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Stats UDP-Proxy",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select non_negative_derivative(min(\"udp.connections-received\"), 1s) as \"connections-received\" from \"nom-proxy.server.statistics\" where $timeFilter AND \"host-name\" =~ /^($hostname)$/ group by time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select non_negative_derivative(min(\"udp.connections-proxied\"), 1s) as \"connections-proxied\" from \"nom-proxy.server.statistics\" where $timeFilter AND \"host-name\" =~ /^($hostname)$/ group by time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select non_negative_derivative(min(\"udp.connections-denied\"), 1s) as \"connections-denied\" from \"nom-proxy.server.statistics\" where $timeFilter AND \"host-name\" =~ /^($hostname)$/ group by time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select non_negative_derivative(min(\"udp.connections-failed-lookup\"), 1s) + non_negative_derivative(min(\"udp.connections-failed-upstream\"), 1s) + non_negative_derivative(min(\"udp.connections-no-flow-allocator\"), 1s) as \"connections-failed\" from \"nom-proxy.server.statistics\" where $timeFilter AND \"host-name\" =~ /^($hostname)$/ group by time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Open Connections Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select non_negative_derivative(min(\"current-client-connections\"), 1s) as \"current-client-connections\" from \"nom-proxy.server.statistics\" where $timeFilter AND \"host-name\" =~ /^($hostname)$/ group by time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select non_negative_derivative(min(\"current-open-files\"), 1s) as \"current-open-fd\" from \"nom-proxy.server.statistics\" where $timeFilter AND \"host-name\" =~ /^($hostname)$/ group by time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TLS Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select non_negative_derivative(min(\"tls.connections-received\"), 1s) as \"tls-connections-received\" from \"nom-proxy.server.statistics\" where $timeFilter AND \"host-name\" =~ /^($hostname)$/ group by time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total TLS Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"tls.client-bytes-sent\"), 1s) + non_negative_derivative(min(\"tls.client-bytes-received\"), 1s) + non_negative_derivative(min(\"tls.server-bytes-received\"), 1s) + non_negative_derivative(min(\"tls.server-bytes-sent\"), 1s) AS \"total-bytes\" from \"nom-proxy.server.statistics\" where $timeFilter AND \"host-name\" =~ /^($hostname)$/ group by time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Proxied vs Policy Response Sent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "Select non_negative_derivative(min(\"http.proxied\"), 1s) as \"proxied\" from \"nom-proxy.server.statistics\" where $timeFilter AND \"host-name\" =~ /^($hostname)$/ group by time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select non_negative_derivative(min(\"http.policy-responses-sent\"), 1s) as \"policy-responses-sent\" from \"nom-proxy.server.statistics\" where $timeFilter AND \"host-name\" =~ /^($hostname)$/ group by time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DNS resolution failures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "Select non_negative_derivative(min(\"dns-resolution-failed\"), 1s) as \"dns-resolution-failed\" from \"nom-proxy.server.statistics\" where $timeFilter AND \"host-name\" =~ /^($hostname)$/ group by time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Subscribers and Views count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "Select \"subscriber-count\" from \"nom-proxy.server.statistics\" where $timeFilter AND \"host-name\" =~ /^($hostname)$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "Select \"broken-view\" from \"nom-proxy.server.statistics\" where $timeFilter AND \"host-name\" =~ /^($hostname)$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Kafka-provisioning Update Lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (min(\"kafka-provisioning.current-time\") - min(\"kafka-provisioning.last-update-time\")) AS \"update lag\" FROM \"nom-proxy.layer.status\" where $timeFilter AND \"host-name\" =~ /^($hostname)$/ group by time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}