{
 "title": "Proxies",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Aggregate HTTP-Proxy TPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(rps) as rps from (select non_negative_derivative(min(\"http.requests-received\"), 1s) as rps from \"nom-proxy.server.statistics\" where $timeFilter group by time($interval), \"host-name\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP-Proxy TPS by Server",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"http.requests-received\"), 1s) AS \"rps\" FROM \"nom-proxy.server.statistics\" WHERE $timeFilter GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Aggregate HTTP-Proxy Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(\"total-bytes\") as \"agg-total-bytes\" FROM (SELECT non_negative_derivative(min(\"http.request-bytes-sent\"), 1s) + non_negative_derivative(min(\"http.request-bytes-received\"), 1s) + non_negative_derivative(min(\"http.response-bytes-received\"), 1s) + non_negative_derivative(min(\"http.response-bytes-sent\"), 1s) AS \"total-bytes\" FROM \"nom-proxy.server.statistics\" WHERE $timeFilter GROUP BY time($interval), \"host-name\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP-Proxy Bandwidth by Server",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"http.request-bytes-sent\"), 1s) + non_negative_derivative(min(\"http.response-bytes-received\"), 1s) + non_negative_derivative(min(\"http.request-bytes-received\"), 1s) + non_negative_derivative(min(\"http.response-bytes-sent\"), 1s) AS \"total-bytes\" FROM \"nom-proxy.server.statistics\" WHERE $timeFilter GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Aggregate TCP-Proxy TPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(rps) as \"rps-proxied\" from (select non_negative_derivative(min(\"tcp.connections-proxied\"), 1s) as rps from \"nom-proxy.server.statistics\" where $timeFilter group by time($interval), \"host-name\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(rps) as \"rps-received\" from (select non_negative_derivative(min(\"tcp.connections-received\"), 1s) as rps from \"nom-proxy.server.statistics\" where $timeFilter group by time($interval), \"host-name\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TCP-Proxy TPS by Server",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"tcp.connections-received\"), 1s) AS \"rps\" FROM \"nom-proxy.server.statistics\" WHERE $timeFilter GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Aggregate TCP-Proxy Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(\"total-bytes\") as \"agg-total-bytes\" FROM (SELECT non_negative_derivative(min(\"tcp.server-bytes-sent\"), 1s) + non_negative_derivative(min(\"tcp.server-bytes-received\"), 1s) + non_negative_derivative(min(\"tcp.client-bytes-sent\"), 1s) + non_negative_derivative(min(\"tcp.client-bytes-received\"), 1s) AS \"total-bytes\" FROM \"nom-proxy.server.statistics\" WHERE $timeFilter GROUP BY time($interval), \"host-name\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TCP-Proxy Bandwidth by Server",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"tcp.server-bytes-sent\"), 1s) + non_negative_derivative(min(\"tcp.server-bytes-received\"), 1s) + non_negative_derivative(min(\"tcp.client-bytes-sent\"), 1s) + non_negative_derivative(min(\"tcp.client-bytes-received\"), 1s) AS \"total-bytes\" FROM \"nom-proxy.server.statistics\" WHERE $timeFilter GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Aggregate UDP-Proxy TPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(rps) as \"rps-proxied\" from (select non_negative_derivative(min(\"udp.connections-proxied\"), 1s) as rps from \"nom-proxy.server.statistics\" where $timeFilter group by time($interval), \"host-name\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(rps) as \"rps-received\" from (select non_negative_derivative(min(\"udp.connections-received\"), 1s) as rps from \"nom-proxy.server.statistics\" where $timeFilter group by time($interval), \"host-name\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UDP-Proxy TPS by Server",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"udp.connections-received\"), 1s) AS \"rps\" FROM \"nom-proxy.server.statistics\" WHERE $timeFilter GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Aggregate UDP-Proxy Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(\"total-bytes\") as \"agg-total-bytes\" FROM (SELECT non_negative_derivative(min(\"udp.server-bytes-sent\"), 1s) + non_negative_derivative(min(\"udp.server-bytes-received\"), 1s) + non_negative_derivative(min(\"udp.client-bytes-sent\"), 1s) + non_negative_derivative(min(\"udp.client-bytes-received\"), 1s) AS \"total-bytes\" FROM \"nom-proxy.server.statistics\" WHERE $timeFilter GROUP BY time($interval), \"host-name\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UDP-Proxy Bandwidth by Server",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"udp.server-bytes-sent\"), 1s) + non_negative_derivative(min(\"udp.server-bytes-received\"), 1s) + non_negative_derivative(min(\"udp.client-bytes-sent\"), 1s) + non_negative_derivative(min(\"udp.client-bytes-received\"), 1s) AS \"total-bytes\" FROM \"nom-proxy.server.statistics\" WHERE $timeFilter GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Aggregate TLS Connection Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(rps) as rps from (select non_negative_derivative(min(\"tls.connections-received\"), 1s) as rps from \"nom-proxy.server.statistics\" where $timeFilter group by time($interval), \"host-name\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TLS Connection Rate per Server",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"tls.connections-received\"), 1s) AS \"rps\" FROM \"nom-proxy.server.statistics\" WHERE $timeFilter GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Aggregate TLS Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"total-bytes\") FROM (SELECT non_negative_derivative(min(\"tls.client-bytes-sent\"), 1s) + non_negative_derivative(min(\"tls.client-bytes-received\"), 1s) + non_negative_derivative(min(\"tls.server-bytes-received\"), 1s) + non_negative_derivative(min(\"tls.server-bytes-sent\"), 1s) AS \"total-bytes\" FROM \"nom-proxy.server.statistics\" WHERE $timeFilter GROUP BY time($interval), \"host-name\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TLS  Bandwidth by Server",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"tls.client-bytes-sent\"), 1s) + non_negative_derivative(min(\"tls.client-bytes-received\"), 1s) + non_negative_derivative(min(\"tls.server-bytes-received\"), 1s) + non_negative_derivative(min(\"tls.server-bytes-sent\"), 1s) AS \"total-bytes\" FROM \"nom-proxy.server.statistics\" WHERE $timeFilter GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Proxied vs Policy Response Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(pps) as proxied from (select non_negative_derivative(min(\"http.proxied\"), 1s) as pps from \"nom-proxy.server.statistics\" where $timeFilter group by time($interval), \"host-name\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(dps) as \"policy-responses-sent\" from (select non_negative_derivative(min(\"http.policy-responses-sent\"), 1s) as dps from \"nom-proxy.server.statistics\" where $timeFilter group by time($interval), \"host-name\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Policy Response Rate by Status Code",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(rps) as \"302-responses\" from (select non_negative_derivative(min(\"http.policy-responses-sent-by-status.302\"), 1s) as rps from \"nom-proxy.server.statistics\" where $timeFilter group by time($interval), \"host-name\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(dps) as \"403-responses\" from (select non_negative_derivative(min(\"http.policy-responses-sent-by-status.403\"), 1s) as dps from \"nom-proxy.server.statistics\" where $timeFilter group by time($interval), \"host-name\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(rps) as \"200-responses\" from (select non_negative_derivative(min(\"http.policy-responses-sent-by-status.200\"), 1s) as rps from \"nom-proxy.server.statistics\" where $timeFilter group by time($interval), \"host-name\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Request Error Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(nv) as \"no-view\" FROM (select non_negative_derivative(min(\"no-view\"), 1s) AS \"nv\" FROM \"nom-proxy.server.statistics\" WHERE $timeFilter GROUP BY time($interval), \"host-name\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(oad) as \"outbound-acl-denied\" FROM (select non_negative_derivative(min(\"outbound-acl-denies\"), 1s) AS \"oad\" FROM \"nom-proxy.server.statistics\" WHERE $timeFilter GROUP BY time($interval), \"host-name\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(drf) as \"dns-resolution-failed\" FROM (select non_negative_derivative(min(\"dns-resolution-failed\"), 1s) AS \"drf\" FROM \"nom-proxy.server.statistics\" WHERE $timeFilter GROUP BY time($interval), \"host-name\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(cf) as \"connections-failed\" FROM (select non_negative_derivative(min(\"connections-failed\"), 1s) AS \"cf\" FROM \"nom-proxy.server.statistics\" WHERE $timeFilter GROUP BY time($interval), \"host-name\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP Error Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(brsp) as \"bad-response\" FROM (select non_negative_derivative(min(\"http.bad-response\"), 1s) AS \"brsp\" FROM \"nom-proxy.server.statistics\" WHERE $timeFilter GROUP BY time($interval), \"host-name\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(brq) as \"bad-request\" FROM (select non_negative_derivative(min(\"http.bad-request\"), 1s) AS \"brq\" FROM \"nom-proxy.server.statistics\" WHERE $timeFilter GROUP BY time($interval), \"host-name\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(erd) as \"explicit-request-denied\" FROM (select non_negative_derivative(min(\"http.explicit-requests-denied\"), 1s) AS \"erd\" FROM \"nom-proxy.server.statistics\" WHERE $timeFilter GROUP BY time($interval), \"host-name\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Aggregate TLS Connection Result Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"ich\") AS \"invalid-client-hello\" FROM (SELECT non_negative_derivative(min(\"tls.invalid-client-hello\"), 1s) AS \"ich\" FROM \"nom-proxy.server.statistics\" WHERE $timeFilter GROUP BY time($interval), \"host-name\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"td\") AS \"tunnel-denied\" FROM (SELECT non_negative_derivative(min(\"tls.tunnel-denied\"), 1s) AS \"td\" FROM \"nom-proxy.server.statistics\" WHERE $timeFilter GROUP BY time($interval), \"host-name\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"ta\") AS \"tunnel-allowed\" FROM (SELECT non_negative_derivative(min(\"tls.tunnel-allowed\"), 1s) AS \"ta\" FROM \"nom-proxy.server.statistics\" WHERE $timeFilter GROUP BY time($interval), \"host-name\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Usage by Server",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT min(\"memory-in-use\") AS \"memory\" FROM \"nom-proxy.server.usage\" WHERE $timeFilter GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Proxy User Time by Server",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"user-time\"), 1s) AS \"cpu\" FROM \"nom-proxy.server.usage\" WHERE $timeFilter GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Proxy System Time by Server",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(min(\"system-time\"), 1s) AS \"cpu\" FROM \"nom-proxy.server.usage\" WHERE $timeFilter GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Aggregate Client-Side Bandwidth (HTTP and TLS)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"total-bytes-received\") AS \"bytes-received\" FROM (SELECT non_negative_derivative(min(\"http.request-bytes-received\"), 1s) + non_negative_derivative(min(\"tls.client-bytes-received\"), 1s) AS \"total-bytes-received\" FROM \"nom-proxy.server.statistics\" WHERE $timeFilter GROUP BY time($interval), \"host-name\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"total-bytes-sent\") AS \"bytes-sent\" FROM (SELECT non_negative_derivative(min(\"http.response-bytes-sent\"), 1s) + non_negative_derivative(min(\"tls.client-bytes-sent\"), 1s) AS \"total-bytes-sent\" FROM \"nom-proxy.server.statistics\" WHERE $timeFilter GROUP BY time($interval), \"host-name\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Aggregate OCS Bandwidth (HTTP and TLS)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"total-bytes-sent\") AS \"bytes-sent\" FROM (SELECT non_negative_derivative(min(\"http.request-bytes-sent\"), 1s) + non_negative_derivative(min(\"tls.server-bytes-sent\"), 1s) AS \"total-bytes-sent\" FROM \"nom-proxy.server.statistics\" WHERE $timeFilter GROUP BY time($interval), \"host-name\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"total-bytes-received\") AS \"bytes-received\" FROM (SELECT non_negative_derivative(min(\"http.response-bytes-received\"), 1s) + non_negative_derivative(min(\"tls.server-bytes-received\"), 1s) AS \"total-bytes-received\" FROM \"nom-proxy.server.statistics\" WHERE $timeFilter GROUP BY time($interval), \"host-name\" fill(null)) where $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}