{
 "title": "Stream-proc HTTP-connectors",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Events",
    "query": "show tag values from \"stream-proc.http-connector.statistics\" with key = \"key\""
   }
  ]
 },
 "panels": [
  { "title": "HTTP-endpoint calls", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP-endpoint API calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"call-count\") as \"aggregate-calls-count\" from (SELECT non_negative_derivative(min(\"endpoint-call-count\"), 1s) AS \"call-count\" from \"stream-proc.http-connector.statistics\" where $timeFilter group by time($interval), \"host-name\" fill(null)) where $timeFilter group by time($interval), \"key\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP-endpoint failed API calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"call-count-fail\") as \"aggregate-calls-count-fail\" from (SELECT non_negative_derivative(min(\"endpoint-call-failure-count\"), 1s) AS \"call-count-fail\" from \"stream-proc.http-connector.statistics\" where $timeFilter group by time($interval), \"host-name\" fill(null)) where $timeFilter group by time($interval), \"key\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "HTTP-connector events consumed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"events-consumed\") as \"aggregate-events-consumed\" from (SELECT non_negative_derivative(min(\"events-consumed-count\"), 1s) AS \"events-consumed\" from \"stream-proc.http-connector.statistics\" where $timeFilter group by time($interval), \"host-name\" fill(null)) where $timeFilter group by time($interval), \"key\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP-connector events failed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"events-failed\") as \"aggregate-events-failed\" from (SELECT non_negative_derivative(min(\"events-failed-count\"), 1s) AS \"events-failed\" from \"stream-proc.http-connector.statistics\" where $timeFilter group by time($interval), \"host-name\" fill(null)) where $timeFilter group by time($interval), \"key\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Auth-tokens", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "HTTP-connector auth-tokens failure renew",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"token-failure\") as \"aggregate-token-failure\" from (SELECT non_negative_derivative(min(\"auth-token-failure-count\"), 1s) AS \"token-failure\" from \"stream-proc.http-connector.statistics\" where $timeFilter group by time($interval), \"host-name\" fill(null)) where $timeFilter group by time($interval), \"key\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP-connector auth-tokens success renew",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"token-success\") as \"aggregate-token-success\" from (SELECT non_negative_derivative(min(\"auth-token-success-count\"), 1s) AS \"token-success\" from \"stream-proc.http-connector.statistics\" where $timeFilter group by time($interval), \"host-name\" fill(null)) where $timeFilter group by time($interval), \"key\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}