{
 "title": "Telegraf Dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": "show tag values from \"nom-telegraf.system\" with key = \"host-name\""
   },
   {
    "name": "disk",
    "label": "Disk Name",
    "query": "show tag values from \"nom-telegraf.disk\" with key = \"key\" where \"host-name\" =~ /^($host)$/"
   }
  ]
 },
 "panels": [
  {
   "title": "System Utilization",
   "type": "graph",
   "description": "Normalized to number of CPU cores",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"load1\" / \"n_cpus\" as load1m FROM \"nom-telegraf.system\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"load5\" / \"n_cpus\" as load5m FROM \"nom-telegraf.system\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"load15\" / \"n_cpus\" as load15m FROM \"nom-telegraf.system\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT ( mean(\"available\") + mean(\"used\") ) as total FROM \"nom-telegraf.mem\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY time($interval),  \"host-name\"  fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"used\") as used FROM \"nom-telegraf.mem\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY time($interval),  \"host-name\"  fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"used\") as \"swap-used\" FROM \"nom-telegraf.swap\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY time($interval),  \"host-name\"  fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"usage_system\") as usage_system FROM \"nom-telegraf.cpu\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY time($interval), \"host-name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"usage_user\") as usage_user FROM \"nom-telegraf.cpu\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY time($interval),  \"host-name\"  fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"usage_iowait\") as usage_iowait FROM \"nom-telegraf.cpu\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ GROUP BY time($interval),  \"host-name\"  fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Usage Percent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"used_percent\") as used_percent FROM \"nom-telegraf.disk\" WHERE $timeFilter AND \"host-name\" =~ /^($host)$/ AND \"key\" =~ /^($disk)$/ GROUP BY time($interval), \"host-name\", \"key\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}